version: '3.8'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'devbills'
      MONGO_INITDB_ROOT_PASSWORD: 'pass123'
    ports:
      - '27017:27017'
    networks:
      - local
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  
  app:
    depends_on:
      mongo:
        condition: service_healthy
    container_name: devbills-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://devbills:pass123@mongo:27017
      - FRONT_URL=http://localhost:3000
      - PORT=3333
    volumes:
      - ./:/home/app
    ports:
      - '3333:3333'
    networks:
      - local

networks:
  local:
    name: local